const MESSAGE_ERROR = {
  // auth
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  UNAUTHORIZED: "Unauthorized",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  USER_OR_PASSWORD_INCORRECT: "USER_OR_PASSWORD_INCORRECT",
  CONFIRM_PASSWORD_INCORRECT: "CONFIRM_PASSWORD_INCORRECT",
  TRY_AGAIN: "TRY_AGAIN",

  // structure
  UNIT_IS_EXISTED: "UNIT_IS_EXISTED",

  // collection
  COLLECTION_IS_EXISTED: "COLLECTION_IS_EXISTED",
};

export default MESSAGE_ERROR;
