export enum EProductStatus {
  ALL = "ALL",
  IN_ACTIVE = "INACTIVE",
  ENABLE = "ENABLE",
  DISABLE = "DISABLE",
}

export enum ECollectionStatus {
  ALL = "ALL",
  PENDING = "PENDING",
  MERCHANT_REVIEW = "MERCHANT_REVIEW",
  ADMIN_REVIEW = "ADMIN_REVIEW",
  LISTED = "LISTED",
  UNLISTED = "UNLISTED",
}

export enum ENftStatus {
  ALL = "ALL",
  PENDING = "PENDING",
  MERCHANT_REVIEW = "MERCHANT_REVIEW",
  ADMIN_REVIEW = "ADMIN_REVIEW",
  MINTED = "MINTED",
  LISTED = "LISTED",
  UNLISTED = "UNLISTED",
}

export enum EProductType {
  PROJECT = "PROJECT",
  COLLECTION = "COLLECTION",
  NFT = "NFT",
}
